Repository gcu-LastDance/GachonOJ-Frontend, pull requests merged in 2024-05, with the labels that each got.

#104 [fix] 관리자 대회페이지 오류 수정
  app/admin/contest-manage/page.tsx
Labels: feat ✨

#106 [fix] 오류 수정
  api/adminContestAPI.ts
  app/admin/exam-manage/page.tsx
Labels: fix 💥, 현수

#108 [fix] #107 오류 수정
  app/admin/notice-manage/[noticeId]/_components/NoticeDetailPage.tsx
Labels: fix 💥, 현수

#112 [feat] 교수 관련 api 연동
  api/admin/adminContestAPI.ts
  api/admin/adminExamAPI.ts
  api/admin/adminInquiryAPI.ts
  api/admin/adminNoticeAPI.ts
  api/admin/adminProblemAPI.ts
  api/admin/adminUserAPI.ts
  api/professor/professorExamAPI.ts
  api/professor/professorInfoAPI.ts
  api/professor/professorInquiryAPI.ts
  app/admin/admin-manage/my-account/_components/EditAdminMyAccountForm.tsx
  app/admin/contest-manage/list/_component/ContestManageTable.tsx
  app/admin/exam-manage/list/_components/ExamManageTable.tsx
  app/admin/inquiry-manage/[inquiryId]/_components/Inquiryreplyempty.tsx
  app/admin/inquiry-manage/[inquiryId]/page.tsx
  app/admin/inquiry-manage/_components/InquiryManageTable.tsx
  app/admin/notice-manage/[noticeId]/_components/NoticeDetailPage.tsx
  app/admin/notice-manage/enroll/_components/CreateNoticeForm.tsx
  app/admin/notice-manage/list/_components/NoticeManageTable.tsx
  app/admin/problem-manage/_components/ProblemManageTable.tsx
  app/admin/professor-manage/edit/_components/EditProfessorForm.tsx
  app/admin/professor-manage/enroll/_components/CreateProfessorForm.tsx
  app/admin/professor-manage/list/_components/ProfessorManageTable.tsx
  app/admin/user-manage/edit/_components/EditUserForm.tsx
  app/admin/user-manage/enroll/_components/CreateUserForm.tsx
  app/admin/user-manage/list/_components/userManageTable.tsx
  app/professor/_components/SideProfessorNav.tsx
  app/professor/exam-manage/list/_components/ExamTable.tsx
  app/professor/inquiry/[InquiryId]/page.tsx
  app/professor/inquiry/list/_components/InquiryTable.tsx
  app/professor/inquiry/write/_components/InquriyForm.tsx
  app/professor/my-account/_components/EditProfessorMyAccountForm.tsx
  app/professor/my-account/page.tsx
  app/professor/my-account/withdrawl/page.tsx
  types/professor/user.ts
Labels: feat ✨, 현수

#114 [fix] #113 빌드용 도커파일 수정
  Dockerfile
Labels: fix 💥, 현진

#116 [fix] 빌드 오류 수정
  Dockerfile
  app/(site)/profile/settings/password/page.tsx
  app/(site)/profile/withdrawal/page.tsx
  next.config.mjs
  package.json
  pnpm-lock.yaml
Labels: fix 💥, 현진

#119 [fix] 빌드 오류 해결 및 dockerignore 추가
  Dockerfile
Labels: fix 💥, 현진

#120 [feat[ 관리자 문제 등록 및 수정 api 연동
  api/admin/adminInquiryAPI.ts
  api/admin/adminUserAPI.ts
  api/professor/professorInfoAPI.ts
  app/admin/_components/SideAdminNav.tsx
  app/admin/admin-manage/_components/AdminManageTable.tsx
  app/admin/admin-manage/list/page.tsx
  app/admin/admin-manage/my-account/_components/EditAdminMyAccountForm.tsx
  app/admin/admin-manage/page.tsx
  app/admin/contest-manage/list/_component/ContestManageTable.tsx
  app/admin/exam-manage/list/_components/ExamManageTable.tsx
  app/admin/inquiry-manage/_components/InquiryManageTable.tsx
  app/admin/problem-manage/editor/@modal/(.)testcase/page.tsx
  app/admin/problem-manage/editor/@modal/default.tsx
  app/admin/problem-manage/editor/_components/ProblemForm.tsx
  app/admin/problem-manage/editor/layout.tsx
  app/admin/problem-manage/editor/testcase/page.tsx
  app/admin/problem-manage/list/_components/ProblemManageTable.tsx
  app/admin/problem-manage/list/page.tsx
  app/admin/problem-manage/page.tsx
  app/admin/professor-manage/list/_components/ProfessorManageTable.tsx
  app/admin/user-manage/list/_components/userManageTable.tsx
  app/professor/my-account/_components/EditProfessorMyAccountForm.tsx
  app/professor/my-account/withdrawl/page.tsx
  components/modal/ModalLarge.tsx
  components/nav/manage/BreadCrumbs.tsx
  constants/breadCrumbsMap.ts
  next.config.mjs
  types/admin/problem.ts
  types/admin/user.ts
  types/professor/user.ts
Labels: feat ✨, 현수

#124 [fix] 충돌 오류 수정
  app/admin/admin-manage/my-account/_components/EditAdminMyAccountForm.tsx
  app/admin/problem-manage/list/page.tsx
  app/admin/problem-manage/page.tsx
  app/professor/my-account/_components/EditProfessorMyAccountForm.tsx
Labels: fix 💥, 현진

#126 [feat] 문제 등록 기능 구현
  api/admin/adminProblemAPI.ts
  app/admin/_components/SideAdminNav.tsx
  app/admin/admin-manage/edit/_components/EditAdminForm.tsx
  app/admin/admin-manage/enroll/_components/CreateAdminForm.tsx
  app/admin/admin-manage/my-account/_components/EditAdminMyAccountForm.tsx
  app/admin/notice-manage/enroll/_components/CreateNoticeForm.tsx
  app/admin/problem-manage/enroll/editor/@modal/(.)testcase/page.tsx
  app/admin/problem-manage/enroll/editor/@modal/default.tsx
  app/admin/problem-manage/enroll/editor/_components/ProblemForm.tsx
  app/admin/problem-manage/enroll/editor/layout.tsx
  app/admin/problem-manage/enroll/editor/page.tsx
  app/admin/problem-manage/enroll/editor/testcase/page.tsx
  app/admin/problem-manage/list/_components/ProblemManageTable.tsx
  app/admin/problem-manage/page.tsx
  app/admin/professor-manage/edit/_components/EditProfessorForm.tsx
  app/admin/professor-manage/enroll/_components/CreateProfessorForm.tsx
  app/admin/user-manage/edit/_components/EditUserForm.tsx
  app/admin/user-manage/enroll/_components/CreateUserForm.tsx
  app/professor/_components/SideProfessorNav.tsx
  app/professor/my-account/_components/EditProfessorMyAccountForm.tsx
  store/useTestCaseStore.ts
  types/admin/problem.ts
Labels: feat ✨, 현수

#136 [feat] #95 프론트단 권한 분리 및 강제 라우팅 처리
  app/(auth)/login/_components/LoginForm.tsx
  app/(site)/profile/settings/page.tsx
  app/algorithm-ide/_components/IdeFooter.tsx
  app/layout.tsx
  lib/axiosConfig.ts
  package.json
  pnpm-lock.yaml
Labels: feat ✨, 현진

#138 [feat]페이지네이션 구현
  api/admin/adminDashboardAPI.ts
  api/admin/adminNoticeAPI.ts
  api/admin/adminProblemAPI.ts
  app/admin/_components/HealthCheck.tsx
  app/admin/_components/_HealthCheck/AIService.tsx
  app/admin/_components/_HealthCheck/BoardService.tsx
  app/admin/_components/_HealthCheck/MemberService.tsx
  app/admin/_components/_HealthCheck/ProblemService.tsx
  app/admin/_components/_HealthCheck/SubmissionService.tsx
  app/admin/contest-manage/list/_component/ContestManageTable.tsx
  app/admin/exam-manage/enroll/_components/ProblemForm.tsx
  app/admin/exam-manage/list/_components/ExamManageTable.tsx
  app/admin/inquiry-manage/_components/InquiryManageTable.tsx
  app/admin/notice-manage/list/_components/NoticeManageTable.tsx
  app/admin/page.tsx
  app/admin/problem-manage/edit/editor/_components/ProblemForm.tsx
  app/admin/problem-manage/enroll/editor/_components/ProblemForm.tsx
  app/admin/problem-manage/list/_components/ProblemManageTable.tsx
  app/admin/professor-manage/list/_components/ProfessorManageTable.tsx
  app/admin/user-manage/list/_components/userManageTable.tsx
  app/professor/exam-manage/list/_components/ExamTable.tsx
  app/professor/inquiry/list/_components/InquiryTable.tsx
  components/pagination/PaginationBar.css
  components/pagination/PaginationBar.tsx
  package.json
  pnpm-lock.yaml
  types/admin/problem.ts
Labels: feat ✨, 현수

#142 [feat] 관리자 대시보드 health 상태 구현
  api/admin/adminDashboardAPI.ts
  api/professor/professorExamAPI.ts
  app/admin/_components/AiToken.tsx
  app/admin/_components/HealthCheck.tsx
  app/admin/_components/_HealthCheck/AIService.tsx
  app/admin/_components/_HealthCheck/BoardService.tsx
  app/admin/_components/_HealthCheck/MemberService.tsx
  app/admin/_components/_HealthCheck/ProblemService.tsx
  app/admin/_components/_HealthCheck/SubmissionService.tsx
  app/admin/exam-manage/enroll/_components/EnrollTestForm.tsx
  app/admin/exam-manage/list/_components/ExamManageTable.tsx
  app/admin/inquiry-manage/_components/InquiryManageTable.tsx
  app/admin/notice-manage/list/_components/NoticeManageTable.tsx
  app/admin/page.tsx
  app/admin/problem-manage/list/_components/ProblemManageTable.tsx
  app/admin/professor-manage/list/_components/ProfessorManageTable.tsx
  app/admin/user-manage/list/_components/userManageTable.tsx
  app/professor/_components/SideProfessorNav.tsx
  app/professor/exam-manage/list/_components/ExamTable.tsx
  app/professor/inquiry/list/_components/InquiryTable.tsx
Labels: feat ✨, 현수

#143 Feat/#141 페이지네이션 바 구현
  api/inquiryAPI.ts
  api/memberAPI.ts
  api/noticeAPI.ts
  api/problemAPI.ts
  app/(site)/inquiry/_components/InquiryTable.tsx
  app/(site)/inquiry/page.tsx
  app/(site)/notice/_components/NoticeTable.tsx
  app/(site)/notice/page.tsx
  app/(site)/problem/_components/ProblemTable.tsx
  app/(site)/profile/_components/MemberProblemTable.tsx
  app/(site)/ranking/_components/RankingTable.tsx
  app/admin/inquiry-manage/_components/InquiryManageTable.tsx
  components/pagination/PaginationBar.css
Labels: feat ✨, 현진

#146 [feat] 북마크 기능 구현 랜딩페이지 고도화
  api/problemAPI.ts
  api/testAPI.ts
  app/(landing)/page.tsx
  app/(site)/_components/HeaderNav.tsx
  app/(site)/contest/_components/ContestTable.tsx
  app/(site)/contest/page.tsx
  app/(site)/exam/_components/ExamTable.tsx
  app/(site)/exam/page.tsx
  app/(site)/problem/_components/ProblemTable.tsx
  app/(site)/problem/page.tsx
  app/(site)/profile/_components/MemberProblemTable.tsx
  app/(site)/profile/page.tsx
  app/(site)/ranking/page.tsx
  components/card/MemberProbInfoCard.tsx
  components/footer/SiteFooter.tsx
  public/images/banner/default_banner_img.png
Labels: feat ✨, 현진

#151 [feat] 문제 제출이력 관련 기능 구현 ai 분석 페이지 퍼블리싱 메인 페이지 캐러셀 추가
  api/problemAPI.ts
  api/testAPI.ts
  app/(site)/_components/HeaderMemberDropdown.tsx
  app/(site)/exam/[examId]/page.tsx
  app/(site)/exam/_components/ExamTable.tsx
  app/(site)/main/_components/MainBanner.tsx
  app/(site)/main/page.tsx
  app/(site)/problem/_components/ProblemTable.tsx
  app/(site)/problem/feedback/[submissionId]/page.tsx
  app/(site)/profile/_components/MemberProblemTable.tsx
  app/(site)/profile/_components/MemberSolProblemTable.tsx
  app/algorithm-ide/[problemId]/history/page.tsx
  app/algorithm-ide/[problemId]/page.tsx
  app/algorithm-ide/_components/HistoryModal.tsx
  app/algorithm-ide/_components/IdeFooter.tsx
  app/algorithm-ide/_components/IdeMain.tsx
  app/test-ide/@modal/(.)[problemId]/history/page.tsx
  app/test-ide/@modal/(.)setting/page.tsx
  app/test-ide/[examId]/page.tsx
  app/test-ide/[problemId]/history/page.tsx
  app/test-ide/[problemId]/page.tsx
  app/test-ide/_components/HistoryModal.tsx
  app/test-ide/_components/IdeFooter.tsx
  app/test-ide/_components/IdeMain.tsx
  app/test-ide/_components/IdeProblemWindow.tsx
  app/test-ide/_components/IdeResultWindow.tsx
  app/test-ide/_components/ResultModal.tsx
  package.json
  pnpm-lock.yaml
  public/images/banner/banner_1_img.png
  public/images/banner/banner_2_img.png
  public/images/banner/banner_3_img.png
  types/problem.ts
Labels: feat ✨, 현진

#155 [feat] 시험 및 대회 ide 관련 기능 구현 ide 다크모드 지원 구현
  api/testAPI.ts
  app/algorithm-ide/@modal/(.)setting/page.tsx
  app/algorithm-ide/[problemId]/page.tsx
  app/algorithm-ide/_components/HistoryModal.tsx
  app/algorithm-ide/_components/IdeMain.tsx
  app/algorithm-ide/_components/ResultModal.tsx
  app/test-ide/@modal/(.)setting/page.tsx
  app/test-ide/[examId]/_components/ProbNavModal.tsx
  app/test-ide/[examId]/page.tsx
  app/test-ide/_components/HistoryModal.tsx
  app/test-ide/_components/IdeFooter.tsx
  app/test-ide/_components/IdeMain.tsx
  app/test-ide/_components/IdeProblemWindow.tsx
  app/test-ide/_components/ResultModal.tsx
  public/images/banner/banner_1_img.png
  public/images/banner/banner_2_img.png
  public/images/banner/banner_3_img.png
  store/useIdeLightOnDarkStore.ts
  types/test.ts
Labels: feat ✨, 현진

#156 [feat] 시험 결과 목록 및 상세 조회 연동
  api/admin/adminContestAPI.ts
  api/admin/adminDashboardAPI.ts
  api/admin/adminExamAPI.ts
  api/admin/adminProblemAPI.ts
  api/professor/professorExamAPI.ts
  api/professor/professorInquiryAPI.ts
  app/admin/_components/AiToken.tsx
  app/admin/_components/CodeViewer.tsx
  app/admin/_components/HealthCheck.tsx
  app/admin/_components/InquiryList.tsx
  app/admin/_components/TodaySubmission.tsx
  app/admin/contest-manage/edit/_components/EditContestForm.tsx
  app/admin/contest-manage/edit/page.tsx
  app/admin/contest-manage/enroll/_components/EnrollContestForm.tsx
  app/admin/contest-manage/enroll/page.tsx
  app/admin/contest-manage/list/_component/ContestManageTable.tsx
  app/admin/contest-manage/result/[testId]/_components/ExamResult.tsx
  app/admin/contest-manage/result/[testId]/page.tsx
  app/admin/contest-manage/result/list/[examId]/_components/ExamResultList.tsx
  app/admin/contest-manage/result/list/[examId]/page.tsx
  app/admin/exam-manage/list/_components/ExamManageTable.tsx
  app/admin/exam-manage/result/[testId]/_components/ExamResult.tsx
  app/admin/exam-manage/result/[testId]/page.tsx
  app/admin/exam-manage/result/list/[examId]/_components/ExamResultList.tsx
  app/admin/exam-manage/result/list/[examId]/page.tsx
  app/admin/inquiry-manage/[inquiryId]/_components/Inquiryreplyempty.tsx
  app/admin/inquiry-manage/[inquiryId]/page.tsx
  app/admin/inquiry-manage/_components/InquiryManageTable.tsx
  app/admin/notice-manage/list/_components/NoticeManageTable.tsx
  app/admin/page.tsx
  app/admin/problem-manage/list/_components/ProblemManageTable.tsx
  app/admin/professor-manage/list/_components/ProfessorManageTable.tsx
  app/admin/user-manage/list/_components/userManageTable.tsx
  app/algorithm-ide/_components/IdeMain.tsx
  app/professor/_components/LanguageGraph.tsx
  app/professor/_components/OngoingExams.tsx
  app/professor/exam-manage/list/_components/ExamTable.tsx
  app/professor/inquiry/list/_components/InquiryTable.tsx
  app/professor/page.tsx
  constants/breadCrumbsMap.ts
  lib/copyClipboard.tsx
  package.json
  pnpm-lock.yaml
  types/admin/exam.ts
Labels: feat ✨, 현수

#159 [fix] 기타 오류사항 수정
  app/admin/inquiry-manage/[inquiryId]/_components/Inquiryreply.tsx
  app/admin/inquiry-manage/[inquiryId]/page.tsx
  app/admin/notice-manage/[noticeId]/_components/NoticeDetailPage.tsx
  app/admin/notice-manage/enroll/_components/CreateNoticeForm.tsx
  app/admin/notice-manage/list/_components/NoticeManageTable.tsx
  app/admin/problem-manage/edit/editor/_components/ProblemForm.tsx
  app/admin/user-manage/enroll/_components/CreateUserForm.tsx
Labels: fix 💥, 현수

#161 [feat] 모달 관련 수정사항 반영 북마크 개선 css 수정
  api/memberAPI.ts
  api/problemAPI.ts
  api/testAPI.ts
  app/(auth)/login/_components/LoginForm.tsx
  app/(auth)/signup/_components/SignupForm.tsx
  app/(site)/contest/[examId]/page.tsx
  app/(site)/exam/[examId]/page.tsx
  app/(site)/main/_components/MainBanner.tsx
  app/(site)/problem/_components/ProblemTable.tsx
  app/algorithm-ide/_components/HistoryModal.tsx
  app/test-ide/_components/IdeFooter.tsx
  app/test-ide/_components/IdeProblemWindow.tsx
  components/modal/ModalLarge.tsx
  components/modal/ModalSmall.tsx
  public/images/banner/banner_1_img.png
  public/images/banner/banner_2_img.png
  public/images/banner/banner_3_img.png
  public/images/banner/banner_4_img.png
Labels: feat ✨, 현진

#165 [feat] 로딩 애니메이션 및 css 수정
  app/(site)/contest/[examId]/page.tsx
  app/(site)/exam/[examId]/page.tsx
  app/(site)/problem/feedback/[submissionId]/page.tsx
  app/(site)/profile/@modal/(.)withdrawal/page.tsx
  app/(site)/profile/_components/MemberProblemTable.tsx
  app/(site)/profile/_components/MemberSolProblemTable.tsx
  app/(site)/profile/settings/page.tsx
  app/test-ide/_components/IdeMain.tsx
Labels: feat ✨, 현진

#167 [fix] type 오류수정
  app/admin/contest-manage/edit/_components/EditContestForm.tsx
  app/admin/contest-manage/enroll/_components/EnrollContestForm.tsx
Labels: fix 💥, 현수
