Repository gcu-LastDance/GachonOJ-Frontend, pull requests merged in 2024-06, with the labels that each got.

#172 [fix] 교수 시험 목록 페이지네이션 문제 등록시 분류 유지
  api/professor/professorExamAPI.ts
  app/admin/exam-manage/edit/_components/ProblemForm.tsx
  app/admin/exam-manage/enroll/_components/ProblemForm.tsx
  app/admin/problem-manage/edit/editor/_components/ProblemForm.tsx
  app/professor/exam-manage/list/_components/ExamTable.tsx
  lib/copyClipboard.tsx
  mocks/ADMIN_MOCK_DATA.json
  mocks/PROBLEM_MOCK_DATA.json
Labels: fix 💥, 현수

#173 [feat] 시험 테스트케이스 세션 관리 알고리즘 문제 코드 세션 관리 일부 api 연동 확인 ai 피드
  app/(site)/_components/HeaderMemberDropdown.tsx
  app/(site)/_components/HeaderNav.tsx
  app/(site)/profile/_components/MemberProblemTable.tsx
  app/(site)/profile/_components/MemberSolProblemTable.tsx
  app/admin/admin-manage/page.tsx
  app/algorithm-ide/_components/IdeHeaderMemberDropdown.tsx
  app/test-ide/[examId]/page.tsx
  app/test-ide/_components/IdeHeaderMemberDropdown.tsx
  components/nav/manage/AdminHeader.tsx
  lib/axiosConfig.ts
Labels: feat ✨, 현진

#175 [mod] 시험, 대회 삭제 API 수정
  api/admin/adminContestAPI.ts
  api/admin/adminExamAPI.ts
  app/admin/contest-manage/list/_component/ContestManageTable.tsx
  app/admin/exam-manage/list/_components/ExamManageTable.tsx
Labels: mod 〰, 현수

#176 [docs] readme 파일 작성
  README.md
Labels: docs 📄, 현수

#178 [feat] 버그 수정
  app/(site)/profile/_components/MemberSolProblemTable.tsx
  app/algorithm-ide/_components/ResultModal.tsx
Labels: fix 💥, 현진
